### PR TITLE
Optional jquery-injection support.

### PR DESCRIPTION
**Pull request by sharkdp**
It seems that jquery injection is not included in chromedotfiles on purpose. If, however, you are interested in optional support, I have added the funcitonality and an options page for the extension where jquery injection can be enabled. It is disabled by default. If it is enabled, jquery will only be injected into websites which have a corresponding `~/.chromdotfiles` script.

### CODE REVIEW

**Comment by matthewhadley** [comment]
Sorry I missed this PR; I missed a few notices when I was out on paternity.

I'd like to explore having a single script in the user's chrome dotfiles directory that can be included in all sites by default, alongside any file (or not) for a specific site being visited. Then it's up to the user to drop in jquery or whatever other library (underscore, lodash, etc) directly into that file. That way chrome dotfiles doesn't ship with a version of jquery that can become outdated and there's flexibility in what's injected

**Comment by matthewhadley** [comment]
I've added the option to run a `default.js` for every domain (which you can drop jquery into). I've also added the error checking you had. Thanks for idea and PR!

**Comment by sharkdp** [comment]
Thanks for considering this. The downside I see with the `default.js` version is that I would have to inject jquery/underscore/.. into _every_ single site I visit (probably increasing the time to load the page). Another idea would be to have something like `require("jquery.js")`, which would load other scripts from my `~/.js` folder. I'm not sure if this is possible with the Chrome Tabs API.. but I could look into this.

In the end, I can also simply manually copy a version of jquery into the scripts I want to inject.

**Comment by hbt** [comment]
@sharkdp 
Implemented the `require("jquery.js")` idea 
Named the function `loadJS`


It accepts multiple files, can load them async or in sync and accepts a callback.

Available here: https://github.com/hbt/chromedotfiles

Thanks

**Comment by sharkdp** [comment]
Very cool, Thanks!

**Pull request closed without merging**
